### ISSUE TITLE
k-means elbow

### ISSUE THREAD

**Issue by Kokan** [zooflavor/ttaf#1]
Use the elbow method to find number of clusters for k-means.

**Comment by zooflavor** [comment]
Done.
The type ClusteringStrategy is used to abstract away the peculiarities of different clustering methods.
This can describe:
- Different basic methods, like Lloyd's algorithm, ISODATA, or Otsu's method.
- Different parameters of the methods mentioned above, for example, number of clusters, or selecting the initial cluster centers.
- Combinations of all of these, like:
  - best() selects the strategy from a list that has the smallest error.
  - elbow() increases the number of clusters while the error seems to decrease significantly.
