### ISSUE TITLE
implement HSV colorspace

### ISSUE THREAD

**Issue by Kokan** [zooflavor/ttaf#14]
Implement the required interfaces for HSV (distance, addition, subtraction, ...)

**Comment by zooflavor** [comment]
I've implemented a helper class for color conversion, Color.Converter.
This can convert between RGB, HSL, ans HSV.
The class can be used only single threaded, and avoids allocations.

I'm not really sure how much we should take color models seriously.
While strict color models would be nice, it has some serious drawbacks.
Some of the issues are:
- With poorly defined color models all results are ill-defined.
- Significantly increases code complexity.
- We'd need data with color model explicitly stated, which is hard to come by.

**Comment by zooflavor** [comment]
There are 3 hue-like image transformers now:
- Hue treats a 3 channel input as RGB and produces 1 hue channel
- HyperHue takes any-dimensional input and zeros out the coordinate parallel to (1, 1, 1, ..., 1). This is based on the paper https://pubmed.ncbi.nlm.nih.gov/28375322/
- NormalizedHyperHue first projects all data points as HyperHue. After that if the remainder's length is close to zero, it truncates that data point to zero. If the remainder's length is not too close to zero then the datapoint's length will be normalized to 1.
